export const MARKER_PLACED = 'MARKER_PLACED';
export const MARKER_REMOVED = 'MARKER_REMOVED';

export const ROUTE_REQUESTED = 'ROUTE_REQUESTED';
export const ROUTE_SUCCESS = 'ROUTE_SUCCESS';
export const ROUTE_FAILED = 'ROUTE_FAILED';
