export const MARKER_PLACED = 'MARKER_PLACED';
export const MARKER_REMOVED = 'MARKER_REMOVED';
export const ROUTE_REQUESTED = 'ROUTE_REQUESTED';
export const ROUTE_RECEIVED = 'ROUTE_RECEIVED';
export const ROUTE_FAILED = 'ROUTE_FAILED';
